modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "slash_unlimited"
version = "${version}"
displayName = "slash_unlimited"
authors = "DogeisCut"
description = '''
Command limits no more.
'''
#logoFile = ""

[[dependencies.slash_unlimited]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slash_unlimited]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slash_unlimited]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "slash_unlimited.mixins.json"
