modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "slash_unlimited"
version = "${version}"
displayName = "/unlimited"
authors = "DogeisCut"
description = '''
Command limits no more.
'''
logoFile = "assets/slash_unlimited/icon.png"

[[dependencies.slash_unlimited]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slash_unlimited]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "slash_unlimited.mixins.json"
